### ISSUE TITLE
Build error after updating boost to 1.76.0

### ISSUE THREAD

**Issue by sheerluck** [Macaulay2/M2#2078]
```
boost-regex.cpp: In function 'M2_string_struct* regex_replace(M2_string, int, int, M2_string, M2_string, int, int)':
boost-regex.cpp:107:42: error: variable 'std::ostringstream stream' has initializer but incomplete type
  107 |   std::ostringstream stream(std::ios::out);
      |                                          ^
compilation terminated due to -Wfatal-errors.
```

solved by adding `#include <sstream>` to `M2/Macaulay2/d/boost-regex.cpp`

**Comment by DanGrayson** [comment]
Thanks, I'll add the line.
