### ISSUE TITLE
When building on MacOS with gcc-8 normaliz fails to link

### ISSUE THREAD

**Issue by tom111** [Macaulay2/M2#881]
This is the error message I get on the master branch when configuring with:
`CC=gcc-8 CXX=g++-8 CPP=cpp-8 LD=gcc-8 ../../configure --enable-download`:
```
libtool: link: g++-8 -fopenmp -isystem /Users/tom/M2-github-main/M2/BUILD/tomgcc/../../include -isystem /Users/tom/M2-github-main/M2/BUILD/tomgcc/include -isystem /Users/tom/M2-github-main/M2/BUILD/tomgcc/usr-host/include -isystem /Users/tom/M2-github-main/M2/BUILD/tomgcc/usr-host/include/cdd -I/Users/tom/M2-github-main/M2/BUILD/tomgcc/../../submodules/memtailor/src -I/Users/tom/M2-github-main/M2/BUILD/tomgcc/../../submodules/mathic/src -I/Users/tom/M2-github-main/M2/BUILD/tomgcc/../../submodules/mathicgb/src -I/Users/tom/M2-github-main/M2/BUILD/tomgcc/../../submodules/fflas_ffpack/src -isystem /usr/include/libxml2 -isystem /usr/local/Cellar/libatomic_ops/7.6.6/include -DNDEBUG -Wall -O3 -Wno-unknown-pragmas -std=c++11 -I .. -I . -Wno-unknown-pragmas -DNO_OPENMP -g3 -headerpad_max_install_names -o normaliz normaliz.o -Wl,-bind_at_load  -L/Users/tom/M2-github-main/M2/BUILD/tomgcc/usr-host/lib -L/Users/tom/M2-github-main/M2/BUILD/tomgcc/submodules/memtailor/.libs -L/Users/tom/M2-github-main/M2/BUILD/tomgcc/submodules/mathic/.libs -L/Users/tom/M2-github-main/M2/BUILD/tomgcc/submodules/mathicgb/.libs ./.libs/libnormaliz.a -lflint -lmpfr -lgc -lgmpxx -lgmp -lpthread -fopenmp
ld: warning: directory not found for option '-L/Users/tom/M2-github-main/M2/BUILD/tomgcc/submodules/memtailor/.libs'
ld: warning: directory not found for option '-L/Users/tom/M2-github-main/M2/BUILD/tomgcc/submodules/mathic/.libs'
ld: warning: directory not found for option '-L/Users/tom/M2-github-main/M2/BUILD/tomgcc/submodules/mathicgb/.libs'
Undefined symbols for architecture x86_64:
  "___gmpn_com", referenced from:
      __fmpz_vec_get_fft in libflint.a(fmpz_vec_get_fft.o)
      __fmpz_vec_set_fft in libflint.a(fmpz_vec_set_fft.o)
      _fft_mulmod_2expp1 in libflint.a(fft_mulmod_2expp1.o)
      _fmpz_bit_pack in libflint.a(fmpz_bit_pack.o)
      _fmpz_bit_unpack in libflint.a(fmpz_bit_unpack.o)
      _fft_butterfly_twiddle in libflint.a(fft_fft_mfa_truncate_sqrt2.o)
      _fft_butterfly_sqrt2 in libflint.a(fft_fft_truncate_sqrt2.o)
      ...
     (maybe you meant: ___gmpn_com_n)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
gmake[4]: *** [Makefile:615: normaliz] Error 1
```

**Comment by tom111** [comment]
this is what I find in thes
```
> nm -o usr-host/lib/libgmp.a usr-host/lib/libflint.a| grep gmpn_com
usr-host/lib/libgmp.a:aorsmul_i.o:                  U ___gmpn_com_n
usr-host/lib/libgmp.a:cfdiv_r_2exp.o:                  U ___gmpn_com_n
usr-host/lib/libgmp.a:lt87-invert.o:                  U ___gmpn_com_n
usr-host/lib/libgmp.a:toom4_mul_n.o:                  U ___gmpn_com_n
usr-host/lib/libgmp.a:com_n.o: 0000000000000000 T ___gmpn_com_n
usr-host/lib/libgmp.a:neg_n.o:                  U ___gmpn_com_n
usr-host/lib/libflint.a:fmpz_bit_pack.o:                  U ___gmpn_com
usr-host/lib/libflint.a:fmpz_bit_unpack.o:                  U ___gmpn_com
usr-host/lib/libflint.a:fmpz_vec_get_fft.o:                  U ___gmpn_com
usr-host/lib/libflint.a:fmpz_vec_set_fft.o:                  U ___gmpn_com
usr-host/lib/libflint.a:mpn_extras_mulmod_2expp1_basecase.o:                  U ___gmpn_com
usr-host/lib/libflint.a:fft_adjust.o:                  U ___gmpn_com
usr-host/lib/libflint.a:fft_adjust_sqrt2.o:                  U ___gmpn_com
usr-host/lib/libflint.a:fft_butterfly_lshB.o:                  U ___gmpn_com
usr-host/lib/libflint.a:fft_butterfly_rshB.o:                  U ___gmpn_com
usr-host/lib/libflint.a:fft_fermat_to_mpz.o:                  U ___gmpn_com
usr-host/lib/libflint.a:fft_fft_mfa_truncate_sqrt2.o:                  U ___gmpn_com
usr-host/lib/libflint.a:fft_fft_truncate_sqrt2.o:                  U ___gmpn_com
usr-host/lib/libflint.a:fft_ifft_mfa_truncate_sqrt2.o:                  U ___gmpn_com
usr-host/lib/libflint.a:fft_ifft_negacyclic.o:                  U ___gmpn_com
usr-host/lib/libflint.a:fft_ifft_truncate_sqrt2.o:                  U ___gmpn_com
usr-host/lib/libflint.a:fft_mulmod_2expp1.o:                  U ___gmpn_com

```

**Comment by DanGrayson** [comment]
I think the problem is that the way I implemented dependency of our libraries on one another is by listing them in the correct linear order in the makefiles, but if you run "make" with something like "-j4" you might build flint before building mpir, and then it would get linked against the system's gmp, which has different definitions in its include files (differing in whether to use gmpn_com_n or gmpn_com).

So, try "make clean" in the libraries' build directory followed by "make".

**Comment by DanGrayson** [comment]
Let me know whether you did use something like "-j4" with "make".

**Comment by tom111** [comment]
I did originally use "-j4", but now I just reproduced the issue without "-j".  I also checked on the ".compiled" files that mpir was compiled and installed exactly 21 minutes before flint.

Could it be that a system-built gmp is in the way? I noticed that gmp was not built by Macaulay2's build system (it uses mpir, right?). Maybe normaliz tries to link against a system wide gmp?

Also this issue is new. When I was testing for the SOS integration, it worked just fine for a while, for example Oct 30 I reported that gcc-8 works (but the branch was a bit behind master). On Nov 7 I reported on this problem also in pull request 850 and then created this issue here. 

I will start a git bisect from Sep 20 to see when the issue was caused.

**Comment by DanGrayson** [comment]
I don't see how anything in the system could be in the way, but try this:  from the output appearing during the compilation of flint, started by using the command `make QUIET_CC= QUIET_CXX= QUIET_AR=` to get details, grab a random compilation line, add -v to it, and run it from the shell in the appropriate directory as indicated by the preceding line that says `Entering directory`.  Then you'll get a display of the search order for include files, like this:
```
ignoring nonexistent directory "/Users/dan/src/M2/M2/M2/submodules/fflas_ffpack/src"
ignoring duplicate directory "/Users/dan/src/M2/M2/M2/BUILD/dan/builds.tmp/einsteinium-master/usr-host/include"
ignoring duplicate directory "/Users/dan/src/M2/M2/M2/BUILD/dan/builds.tmp/einsteinium-master/usr-host/include"
  as it is a non-system directory that duplicates a system directory
ignoring duplicate directory "/usr/local/include"
  as it is a non-system directory that duplicates a system directory
#include "..." search starts here:
#include <...> search starts here:
 /Users/dan/src/M2/M2/M2/submodules/memtailor/src
 /Users/dan/src/M2/M2/M2/submodules/mathic/src
 /Users/dan/src/M2/M2/M2/submodules/mathicgb/src
 /usr/local/opt/readline/include
 /Users/dan/src/M2/M2/M2/BUILD/dan/builds.tmp/einsteinium-master/libraries/flint/build/flint-2.5.2
 /usr/local
 /Users/dan/src/M2/M2/M2/include
 /Users/dan/src/M2/M2/M2/BUILD/dan/builds.tmp/einsteinium-master/include
 /Users/dan/src/M2/M2/M2/BUILD/dan/builds.tmp/einsteinium-master/usr-host/include
 /Users/dan/src/M2/M2/M2/BUILD/dan/builds.tmp/einsteinium-master/usr-host/include/cdd
 /usr/include/libxml2
 /usr/local/Cellar/libatomic_ops/7.6.6/include
 /usr/local/include
 /Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include
 /Library/Developer/CommandLineTools/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
```
Then you can see whether our `usr-host/include` is the first thing on the path containing `gmp.h`.

**Comment by tom111** [comment]
Here is how it looks for me. Yes, `/usr/local/include` comes before `/Users/tom/M2-github-main/M2/BUILD/tom3/usr-host/include`. What to do about it?
```
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/local/include"
ignoring nonexistent directory "/usr/local/Cellar/gcc/8.2.0/lib/gcc/8/gcc/x86_64-apple-darwin18.0.0/8.2.0/../../../../../../x86_64-apple-darwin18.0.0/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/Library/Frameworks"
ignoring nonexistent directory "/Users/tom/M2-github-main/M2/BUILD/tom3/../../submodules/fflas_ffpack/src"
ignoring duplicate directory "/Users/tom/M2-github-main/M2/BUILD/tom3/usr-host/include"
  as it is a non-system directory that duplicates a system directory
ignoring duplicate directory "/Users/tom/M2-github-main/M2/BUILD/tom3/usr-host/include"
  as it is a non-system directory that duplicates a system directory
#include "..." search starts here:
#include <...> search starts here:
 /Users/tom/M2-github-main/M2/BUILD/tom3/../../submodules/memtailor/src
 /Users/tom/M2-github-main/M2/BUILD/tom3/../../submodules/mathic/src
 /Users/tom/M2-github-main/M2/BUILD/tom3/../../submodules/mathicgb/src
 /Users/tom/M2-github-main/M2/BUILD/tom3/libraries/flint/build/flint-2.5.2
 /usr/local
 /usr/local/include
 /Users/tom/M2-github-main/M2/BUILD/tom3/../../include
 /Users/tom/M2-github-main/M2/BUILD/tom3/include
 /Users/tom/M2-github-main/M2/BUILD/tom3/usr-host/include
 /Users/tom/M2-github-main/M2/BUILD/tom3/usr-host/include/cdd
 /usr/include/libxml2
 /usr/local/Cellar/libatomic_ops/7.6.6/include
 /usr/local/Cellar/gcc/8.2.0/lib/gcc/8/gcc/x86_64-apple-darwin18.0.0/8.2.0/include
 /usr/local/Cellar/gcc/8.2.0/lib/gcc/8/gcc/x86_64-apple-darwin18.0.0/8.2.0/include-fixed
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks
End of search list.
GNU C11 (Homebrew GCC 8.2.0) version 8.2.0 (x86_64-apple-darwin18.0.0)
	compiled by GNU C version 8.2.0, GMP version 6.1.2, MPFR version 4.0.1, MPC version 1.1.0, isl version isl-0.20-GMP
```

**Comment by DanGrayson** [comment]
Try this:
```
diff --git a/M2/include/config.Makefile.in b/M2/include/config.Makefile.in
index 02459683c..9652f26ac 100644
--- a/M2/include/config.Makefile.in
+++ b/M2/include/config.Makefile.in
@@ -78,10 +78,10 @@ GTEST_DIR = @abs_top_builddir@/libraries/final/gtest
 
 # Using -isystem instead of -I here will exclude the files found in those directories from the *.dep files created with the -MM option:
 CPPFLAGS :=									\
-	-isystem @abs_top_srcdir@/include					\
-	-isystem @abs_top_builddir@/include					\
-	-isystem $(BUILTLIBPATH)/include					\
-	-isystem $(BUILTLIBPATH)/include/cdd					\
+	-I@abs_top_srcdir@/include					\
+	-I@abs_top_builddir@/include					\
+	-I$(BUILTLIBPATH)/include					\
+	-I$(BUILTLIBPATH)/include/cdd					\
 	$(foreach S, @BUILDSUBLIST@, -I@abs_top_srcdir@/submodules/$S/src)	\
 	$(CPPFLAGS)
 
```

**Comment by tom111** [comment]
I think with this change aren't you undoing the fix to the following problem:

```
=== making .compiled-062 in lrslib
+ set +x
make: Entering directory '/Users/tom/M2-toms-fork-on-github/M2/BUILD/tom-dan-patch/libraries/lrslib/build/lrslib-062'
+ gmake -j1 prefix=/Users/tom/M2-toms-fork-on-github/M2/BUILD/tom-dan-patch/usr-host 'LDFLAGS=-L/Users/tom/M2-toms-fork-on-github/M2/BUILD/tom-dan-patch/usr-host/lib  -L/Users/tom/M2-toms-fork-on-github/M2/BUILD/tom-dan-patch/submodules/memtailor/.libs  -L/Users/tom/M2-toms-fork-on-github/M2/BUILD/tom-dan-patch/submodules/mathic/.libs  -L/Users/tom/M2-toms-fork-on-github/M2/BUILD/tom-dan-patch/submodules/mathicgb/.libs -g3 -headerpad_max_install_names' CC=gcc-8 TARGET_ARCH= RANLIB=true lrs
gmake[3]: Entering directory '/Users/tom/M2-toms-fork-on-github/M2/BUILD/tom-dan-patch/libraries/lrslib/build/lrslib-062'
gmake[3]: warning: -jN forced in submake: disabling jobserver mode.
gcc-8 -c -O3  -DTIMES -DSIGNALS -DGMP -o lrslib-GMP.o lrslib.c
In file included from lrslib.h:51,
                 from lrslib.c:27:
lrsgmp.h:33:10: fatal error: gmp.h: No such file or directory
 #include "gmp.h"
          ^~~~~~~
compilation terminated.
```

With your patch I run into this again.

For the records. Here is the result of git bisect:

```
20502c65dc947481518f7fe25d7d00b70fe4e1f7 is the first bad commit
commit 20502c65dc947481518f7fe25d7d00b70fe4e1f7
Author: Daniel R. Grayson <dan@math.uiuc.edu>
Date:   Tue Oct 30 20:46:14 2018 +0100

    upgrade normaliz to 3.6.3

:040000 040000 ed61ff652ee45bf604ff5660fe20332d0f877613 430c253f8bd49e6393806539d1ef5aa3d9ab1d2b M	M2
```

It introduced this, which looks suspicious:
```
+# normaliz is linked with flint, which may use gc, and does, for us:
+CONFIGOPTIONS += LIBS=-lgc
```

**Comment by DanGrayson** [comment]
Now the problem seems to be that lrslib gets no CPPFLAGS.  That can't be affected by whether the CPPFLAGS use -I or -isystem.

Why is LIBS=-lgc suspicious?

I think I can simulate what's happening for you by just putting a bogus gmp.h file in /usr/include, one that would cause an error if it is ever read.

**Comment by tom111** [comment]
OK. Sorry for the confusion.  Yes, the compile line for lrslib looks wrong (missing -I, for example).

I can confirm that with your patch (replacing -isystem by -I) normaliz now builds. lrslib is built later, and there the new error occurs.

And 'LIBS="-lgc"' was already removed again in commit 8324b3d81, so it is probably unrelated.

**Comment by DanGrayson** [comment]
Fixed in #40b0b5db369241e14852c8d85da813ae2f86fd55

**Comment by DanGrayson** [comment]
I wonder how that ever worked!

**Comment by tom111** [comment]
Yes, strange.  What about the patch with "-isystem" -> "-I". Will you commit it too?

**Comment by DanGrayson** [comment]
Okay, done in commit dcaa3db2941adb9ce72c5a34b1c76b67a3951334

**Comment by tom111** [comment]
Now it ends like this.  Is there also a "-L" missing ?
```
gcc-8 -c -O3  -I/Users/tom/M2-github-main/M2/BUILD/tom/../../include -I/Users/tom/M2-github-main/M2/BUILD/tom/include -I/Users/tom/M2-github-main/M2/BUILD/tom/usr-host/include -I/Users/tom/M2-github-main/M2/BUILD/tom/usr-host/include/cdd  -I/Users/tom/M2-github-main/M2/BUILD/tom/../../submodules/memtailor/src  -I/Users/tom/M2-github-main/M2/BUILD/tom/../../submodules/mathic/src  -I/Users/tom/M2-github-main/M2/BUILD/tom/../../submodules/mathicgb/src  -I/Users/tom/M2-github-main/M2/BUILD/tom/../../submodules/fflas_ffpack/src -isystem /usr/include/libxml2 -isystem /usr/local/Cellar/libatomic_ops/7.6.6/include  -DNDEBUG -DGMP -o lrs-GMP.o lrs.c
gcc-8 lrs-GMP.o -L. -llrsgmp -L/usr/lib  -lgmp -o lrs
ld: library not found for -lgmp
collect2: error: ld returned 1 exit status
```

**Comment by DanGrayson** [comment]
Yes, try it now.

**Comment by DanGrayson** [comment]
See commit 89bd2bce11c2c10d466d1a2efc25ad38ef1d1552

**Comment by tom111** [comment]
Now in the `/d` directory:

CXX gmp_init.cc
CC gmp_aux.c
CC main.c
CC pari-c.c
CC pari-gnump.c
In file included from ../../../../Macaulay2/d/pari-gnump.c:20:
../../../../Macaulay2/d/pari-gnump.h:31:10: fatal error: mpc.h: No such file or directory
 #include <mpc.h>
          ^~~~~~~
compilation terminated.

**Comment by DanGrayson** [comment]
If you have installed libmpc with brew, that file will be in /usr/local/include.

**Comment by DanGrayson** [comment]
We can also build it for you.  There really should be a test for it in configure.ac.

**Comment by DanGrayson** [comment]
The configure script now checks for mpc.h, closing.
