### ISSUE TITLE
bring givaro up to date

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#513]
Arch Linux includes givaro 4.0.2 as a system package, but our code is compatible only with 3.7.0.  It would be nice to be able just to use it.

**Comment by dimpase** [comment]
AFAIK this is not trivial, they changed the interface quite a bit.

**Comment by DanGrayson** [comment]
Yes, I agree: I tried for 10 minutes and failed.  It seems to me their files might be buggy.

For some reason 3.7.0 doesn't compile either under Arch Linux, so now I'll see if that's trivial to fix.

**Comment by dimpase** [comment]
Sage uses givaro-3.7.1, and it compiles on Arch too.

**Comment by dimpase** [comment]
3.7.1 seems to be nontrivial to locate; you can use the one from http://files.sagemath.org/spkg/upstream/givaro/index.html

**Comment by DanGrayson** [comment]
Found it easily: https://forge.imag.fr/frs/download.php/250/givaro-3.7.1.tar.gz

**Comment by DanGrayson** [comment]
Okay, now I think my problem with Arch Linux is that gcc is up to version 6, and we've never managed to compile all of Macaulay2 against either gcc 5 or gcc 6.

Latest error:
```
g++: internal compiler error: Killed (program cc1plus)
```

**Comment by dimpase** [comment]
Sage does build with gcc-5.3.1, so one might wonder where this fails for M2. Let me see how far I get on Fedora 23, which comes with this gcc.

**Comment by dimpase** [comment]
So, on Fedora 23 master branch fails on PARI:
```
gcc -g -O2 -Wno-unused -pipe -Wall -Wno-shadow -Wcast-qual -Wno-parentheses -Wno-sign-compare  -fno-stack-protector -Wuninitialized -Wwrite-strings -Wstrict-aliasing -Wfatal-errors -Wimplicit-function-declaration -Wno-uninitialized -Wno-cast-qual -Wno-unused -Werror -Wno-unused-label -Wreturn-type -Werror -Wno-error -I. -I./../e -I. -I./../c -I./../regex -I/home/scratch/dimpase/M2/M2/include -I/home/scratch/dimpase/M2/M2/include -I/home/scratch/dimpase/M2/M2/usr-host/include  -I/home/scratch/dimpase/M2/M2/submodules/memtailor/src  -I/home/scratch/dimpase/M2/M2/submodules/mathic/src  -I/home/scratch/dimpase/M2/M2/submodules/mathicgb/src -I/usr/local/include/libxml2 -I/usr/include/libxml2 -I/usr/include/cddlib -I/usr/include/cdd -I/usr/include/glpk  -DNDEBUG -DNDEBUG -Wno-fatal-errors  -c -o pari-gnump.o pari-gnump.c
In file included from pari-gnump.c:20:0:
pari-gnump.h:31:17: fatal error: mpc.h: No such file or directory
compilation terminated.
```
is it  mpc-related?

**Comment by dimpase** [comment]
after installing libmpc-devel
 package, it builds.

**Comment by dimpase** [comment]
Regarding Arch: gcc should be downgraded to gcc 5 in order to build Sagemath. Probably same holds for M2.

**Comment by DanGrayson** [comment]
We've never succeeded building M2 with gcc 5 and getting it to pass all the tests.

**Comment by dimpase** [comment]
please see my reply on #334 - where would you prefer to discuss this?

**Comment by DanGrayson** [comment]
M2 compiles under Arch with gcc 5.4.  Now the tests are running.

**Comment by jakobkroeker** [comment]
maybe https://github.com/Macaulay2/M2/issues/462
and https://github.com/jakobkroeker/M2/commit/f9e79a408e2903f5585e701b9ad9972c932bc4fc
 is also relevant.
(There is unfinished work to upgrade givaro, ffpack and linbox)

**Comment by DanGrayson** [comment]
This adds urgency: "make check" fails with givaro 3.7.1 and clang:
```
/usr/bin/g++ -DHAVE_CONFIG_H -I. -I..  -I..   -I../src/kernel/system -I../src/kernel/memory -I../src/kernel/zpz -I../src/kernel/integer -I../src/kernel -I../src/library/poly1 -I../src/kernel/bstruct -I../src/library/tools -I/Users/dan/src/M2/M2-Macaulay2/M2/include -I/Users/dan/src/M2/M2-Macaulay2/M2/BUILD/dan/builds.tmp/mac64-master-clang-production/include -I/Users/dan/src/M2/M2-Macaulay2/M2/BUILD/dan/builds.tmp/mac64-master-clang-production/usr-host/include  -I/Users/dan/src/M2/M2-Macaulay2/M2/submodules/memtailor/src  -I/Users/dan/src/M2/M2-Macaulay2/M2/submodules/mathic/src  -I/Users/dan/src/M2/M2-Macaulay2/M2/submodules/mathicgb/src -I/usr/include/libxml2 -I/usr/local/Cellar/bdw-gc/7.6.0/include -I/usr/local/Cellar/libatomic_ops/7.4.4/include  -DNDEBUG -O0 -Wall -g -DNDEBUG -UGIVARO_DEBUG -UDEBUG -g -O2 -Wno-mismatched-tags -c -o test-trunc.o test-trunc.C
In file included from test-trunc.C:12:
../src/library/tools/givaro/givtruncdomain.h:17:10: fatal error: 'bits/stl_pair.h' file not
      found
#include <bits/stl_pair.h>
         ^
1 error generated.
gmake[7]: *** [Makefile:454: test-trunc.o] Error 1
```

**Comment by DanGrayson** [comment]
Adding urgency: we can't upgrade fflas-ffpack until givaro is upgraded.

**Comment by dimpase** [comment]
What is the platform here--OS, value of stdlib= used ?  I see this sort of weirdness on Linux, see https://trac.sagemath.org/ticket/12426

**Comment by DanGrayson** [comment]
That was on Mac OS, but just look at the README for fflas-ffpack, which says
this is a requirement:
" * Givaro version at least 4.0.1 (https://github.com/linbox-team/givaro)"

**Comment by dimpase** [comment]
givaro and fflas-ffpack are to be updated in lockstep, yes. I might have time for it in few days.

**Comment by mikestillman** [comment]
This appears to be somewhat involved.  I'm backing it off to the next version.  The real problem seems to be that givaro and another package both take an internal file in gmp, modify it in different ways, and then include it.  So it is hard to include flint and ffpack together, which I don't see an easy way around yet.

**Comment by DanGrayson** [comment]
And then the external symbols conflict?

**Comment by mikestillman** [comment]
Actually, because of templates, the .h files are both needed in the same place, and they conflict.  Probably external symbols would also conflict.  I didn't get that far.  This is all from memory from earlier in the spring.

**Comment by dimpase** [comment]
All `givaro` includes live in `include/givaro/`, I don't get how you can
get header conflict...

**Comment by DanGrayson** [comment]
Now see if we can enable the tests...

**Comment by DanGrayson** [comment]
... tests have been enabled.
