### ISSUE TITLE
Error message when compiling

### ISSUE THREAD

**Issue by zdorovo** [Macaulay2/M2#702]
I got the following error message while compiling the latest release (1.10) from source:

In file included from LPinterface.cc:10:0:
LPinterface.hh:12:21: fatal error: setoper.h: No such file or directory
compilation terminated.

I'm running Linux Mint 18.1 with a 64-bit architecture. Let me know if you need more information

**Comment by DanGrayson** [comment]
You could try cherry picking this fix from the master branch:

https://github.com/Macaulay2/M2/commit/42f023bf2c6913315d9888d07eb3e0e6f80cc4f3

I think that was related.

**Comment by DanGrayson** [comment]
I suspect you are actually compiling from the master branch, where I just noticed I broke that a few days ago, and I fixed it in 36a707b9393f6712a582e3229b3c941d1a7ab621 just now.

**Comment by d-torrance** [comment]
Fixed by https://github.com/Macaulay2/M2/commit/36a707b9393f6712a582e3229b3c941d1a7ab621
