### ISSUE TITLE
Flint 3.2.0

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#3697]
Apparently M2 doesn't build with the version of Flint released a few days ago: https://github.com/Macaulay2/homebrew-tap/issues/261
```cpp
==> cmake --build M2/BUILD/build-brew --target M2-core M2-emacs
Last 15 lines from /Users/ben/Library/Logs/Homebrew/macaulay2/06.cmake:
In file included from /tmp/macaulay2-20250315-29886-cyar5j/M2-release-1.24.11/M2/Macaulay2/e/aring-glue.hpp:7:
In file included from /tmp/macaulay2-20250315-29886-cyar5j/M2-release-1.24.11/M2/Macaulay2/e/aring-translate.hpp:24:
In file included from /tmp/macaulay2-20250315-29886-cyar5j/M2-release-1.24.11/M2/Macaulay2/e/aring-zzp-flint.hpp:22:
In file included from /opt/homebrew/opt/flint/include/flint/nmod.h:22:
In file included from /opt/homebrew/opt/flint/include/flint/ulong_extras.h:26:
/opt/homebrew/opt/flint/include/flint/longlong.h:71:9: warning: '__ll_highpart' macro redefined [-Wmacro-redefined]
   71 | #define __ll_highpart(t) ((ulong) (t) >> (FLINT_BITS / 2))
      |         ^
/opt/homebrew/Cellar/givaro/4.2.0_1/include/recint/reclonglong.h:48:9: note: previous definition is here
   48 | #define __ll_highpart(t) ((UWtype) (t) >> (W_TYPE_SIZE / 2))
      |         ^
3 warnings generated.
```

Moreover, it seems like Factory 4.4.0 (which is ~a year old) may also have an issue: https://github.com/Macaulay2/homebrew-tap/issues/260
```cpp
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I./include -I./include -I. -DFACTORY_BUILDING_DLL -I/usr/local/opt/flint/include/ -I/usr/local/opt/ntl/include -I/usr/local/opt/gmp/include -DSING_NDEBUG -DOM_NDEBUG -std=c++11 -pipe -fno-common -g0 -O3 -Wno-unused-function -Wno-trigraphs -Wno-unused-parameter -Wunknown-pragmas -Wno-unused-variable -fomit-frame-pointer -fwrapv -fvisibility=default -finline-functions -fno-exceptions -fno-threadsafe-statics -funroll-loops -fno-rtti -Qunused-arguments -c facHensel.cc -o facHensel.o >/dev/null 2>&1
facMul.cc:1258:3: error: use of undeclared identifier 'flint_mpn_zero'
  flint_mpn_zero (result->coeffs, d*(degAy+1));
  ^
facMul.cc:1267:5: error: use of undeclared identifier 'flint_mpn_copyi'
    flint_mpn_copyi (result->coeffs+k, buf->coeffs, nmod_poly_length(buf));
    ^
2 errors generated.
make[2]: *** [facMul.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I./include -I./include -I. -DFACTORY_BUILDING_DLL -I/usr/local/opt/flint/include/ -I/usr/local/opt/ntl/include -I/usr/local/opt/gmp/include -DSING_NDEBUG -DOM_NDEBUG -std=c++11 -pipe -fno-common -g0 -O3 -Wno-unused-function -Wno-trigraphs -Wno-unused-parameter -Wunknown-pragmas -Wno-unused-variable -fomit-frame-pointer -fwrapv -fvisibility=default -finline-functions -fno-exceptions -fno-threadsafe-statics -funroll-loops -fno-rtti -Qunused-arguments -c facSparseHensel.cc -o facSparseHensel.o >/dev/null 2>&1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
@d-torrance do you mind producing an archive of Factory-4.4.1 on the website?
This is a regular pain in the neck.

**Comment by mahrud** [comment]
ps: lots of dead links here: https://macaulay2.com/doc/Macaulay2/share/doc/Macaulay2/Macaulay2Doc/html/___Singular-__Factory.html

**Comment by d-torrance** [comment]
Is the brew build using givaro 4.2.1?  This looks like linbox-team/givaro#228, which was fixed a few months ago.

Re: factory -- will do!

**Comment by d-torrance** [comment]
So you can still generate a factory-only tarball by cd'ing into the `factory` directory of the Singular source tree and running `make dist`.  But it's broken and you can't actually build factory from it -- the build requires some files from elsewhere in the Singular source tree that are missing from the tarball.

I think our best bet is to just download the Singular source tarball, cd into `factory`, and run the build with `./configure --without-Singular`.

**Comment by d-torrance** [comment]
I think those warnings aren't the problem, but instead there's an error:

```
CXX aring-gf-flint-big.cpp
In file included from ../../../../Macaulay2/e/aring-gf-flint-big.cpp:3:
../../../../Macaulay2/e/aring-gf-flint-big.hpp: In member function ‘void M2::ARingGFFlintBig::power_mpz(ElementType&, const ElementType&, mpz_srcptr) const’:
../../../../Macaulay2/e/aring-gf-flint-big.hpp:328:5: error: ‘fmpz_init_set_readonly’ was not declared in this scope; did you mean ‘fmpz_init_set_ui’?
  328 |     fmpz_init_set_readonly(fn, abs_n);
      |     ^~~~~~~~~~~~~~~~~~~~~~
      |     fmpz_init_set_ui
```
This is wrapped inside an `#if defined(__GMP_H__)`, and FLINT hasn't been explicitly including `gmp.h` since version 3.2.0.  (See https://github.com/flintlib/flint/commit/3604bb2e4b630bc5a8104d17451badf972810979).  So we should include it ourselves.

I should have a PR soon.

**Comment by d-torrance** [comment]
@mahrud: I figured out how to make a working factory tarball!

https://macaulay2.com/Downloads/OtherSourceCode/factory-4.4.1.tar.gz

**Comment by d-torrance** [comment]
Fixed in #3698
